<a href="https://colab.research.google.com/github/Vaishxx/DL-Projects/blob/main/embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
docs=['go india',
      'india india',
      'hip hip hurrey',
      'jeetega bhai jeetega india jeetega',
      'bharat mata ki jai',
      'kohli kohli',
      'sachin sachin',
      'dhoni dhoni',
      'modi ji ki jai',
      'inquilab zindabad']

In [2]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer=Tokenizer()

In [3]:
tokenizer.fit_on_texts(docs)

In [4]:
len(tokenizer.word_index)

17

In [5]:
sequences=tokenizer.texts_to_sequences(docs)
sequences

[[9, 1],
 [1, 1],
 [3, 3, 10],
 [2, 11, 2, 1, 2],
 [12, 13, 4, 5],
 [6, 6],
 [7, 7],
 [8, 8],
 [14, 15, 4, 5],
 [16, 17]]

In [6]:
from keras.utils import pad_sequences

In [14]:
sequences=pad_sequences(sequences,padding='post',value=17)

In [8]:
sequences

array([[ 9,  1,  0,  0,  0],
       [ 1,  1,  0,  0,  0],
       [ 3,  3, 10,  0,  0],
       [ 2, 11,  2,  1,  2],
       [12, 13,  4,  5,  0],
       [ 6,  6,  0,  0,  0],
       [ 7,  7,  0,  0,  0],
       [ 8,  8,  0,  0,  0],
       [14, 15,  4,  5,  0],
       [16, 17,  0,  0,  0]], dtype=int32)

In [15]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding

model=Sequential()
model.add(Embedding(18,output_dim=2,input_length=5))
model.summary()

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.compile('adam','accuracy')

In [16]:
pred=model.predict(sequences)
print(pred)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step
[[[-0.04764102 -0.02313262]
  [ 0.01482316 -0.04214459]
  [ 0.04252439 -0.00866293]
  [ 0.04252439 -0.00866293]
  [ 0.04252439 -0.00866293]]

 [[ 0.01482316 -0.04214459]
  [ 0.01482316 -0.04214459]
  [ 0.04252439 -0.00866293]
  [ 0.04252439 -0.00866293]
  [ 0.04252439 -0.00866293]]

 [[-0.02006614 -0.03887717]
  [-0.02006614 -0.03887717]
  [ 0.0184968   0.00372683]
  [ 0.04252439 -0.00866293]
  [ 0.04252439 -0.00866293]]

 [[-0.02485073  0.0337995 ]
  [ 0.00462264  0.03341262]
  [-0.02485073  0.0337995 ]
  [ 0.01482316 -0.04214459]
  [-0.02485073  0.0337995 ]]

 [[-0.00807351 -0.04848887]
  [-0.02931129  0.0307533 ]
  [-0.04341934  0.04293361]
  [-0.02910916  0.01533664]
  [ 0.04252439 -0.00866293]]

 [[-0.03030261  0.01429411]
  [-0.03030261  0.01429411]
  [ 0.04252439 -0.00866293]
  [ 0.04252439 -0.00866293]
  [ 0.04252439 -0.00866293]]

 [[ 0.03029363 -0.04448443]
  [ 0.03029363 -0.04448443]
  [ 0.04252439 -0.00866293]
  [ 0.04252439 -0.0086629